import type { BookPart } from './types';
import { Lead, P, H3, List, Ref, Note, ManualFigure, WorkflowStrip } from '../bookPrimitives';
export const partVII : BookPart =   {
    part: 'Part VII â€” Oversight & Alarms',
    chapters: [
      {
        id: 'alerts-triage',
        number: 19,
        title: 'Alert & Notification Center',
        dek: 'Fleet-wide alarm triage, telemetry anomaly surveillance, and event audit',
        body: (
          <>
            <Lead>
              Reachable from the top bar notification bell or directly at <code className="font-sans text-sm font-semibold not-italic">/alerts</code>.
              The Alert &amp; Notification Center is the central triage console for live plant alarms, sensor threshold breaches,
              and historical system notifications across the entire fleet.
            </Lead>
            <Ref
              cols={['Severity Tier', 'Visual Indicator', 'Operational Meaning']}
              rows={[
                ['Critical', 'Red glow Lamp + Rose edge-light', 'Immediate operational threat â€” high TDS, extreme pressure differential (Î”P), critical tank levels, or severe telemetry spike.'],
                ['Warning', 'Amber glow Lamp + Amber edge-light', 'Approaching threshold or abnormal reading requiring supervisor remark or timely inspection.'],
                ['Info / Normal', 'Sky/Teal Lamp + Blue edge-light', 'Routine lifecycle events, PM completions, shift handovers, and informational system notices.'],
              ]}
            />
            <H3>Active Alarms vs. System Log</H3>
            <P>
              The triage console is split into two first-class tabs:
            </P>
            <List
              items={[
                <><strong className="font-sans font-semibold not-italic">Active Alarms</strong> â€” live telemetry conditions generated by sensor thresholds, flow rate deviation guards, and plant status. Active alarms remain visible until resolved, snoozed (1 hour or 24 hours), or dismissed.</>,
                <><strong className="font-sans font-semibold not-italic">System Log</strong> â€” immutable audit records of system events, user approvals, report exports, and broadcast notifications.</>,
              ]}
            />
            <H3>Triage and Batch Controls</H3>
            <P>
              KPI cards at the top provide instant counts for total active alarms, critical alarms, warnings, and unread logs.
              Operators and managers can filter by severity tier, switch between specific plants, search by keyword, or perform
              batch actions (<strong className="font-sans font-semibold not-italic">Snooze All (1h)</strong>,{' '}
              <strong className="font-sans font-semibold not-italic">Dismiss All</strong>, or{' '}
              <strong className="font-sans font-semibold not-italic">Mark All Read</strong>) to streamline high-volume shift changes.
            </P>
            <Note kind="tip">
              The notification bell in the top bar uses an anti-fatigue rate-limiter: it rings once upon the arrival
              of a new critical alarm rather than looping continuously, preventing alarm fatigue on shared shift terminals.
            </Note>
          </>
        ),
      },
      {
        id: 'compliance',
        number: 20,
        title: 'Compliance',
        dek: 'Scoring plants against configurable thresholds',
        body: (
          <>
            <Lead>
              Hidden for Operators. Compliance scores your plant(s) against ten configurable operating
              thresholds across three tabs: Status, Thresholds, and What-if.
            </Lead>
            <Ref
              cols={['Metric', 'Default threshold']}
              rows={[
                ['NRW % (Non-Revenue Water)', 'Max 20%'],
                ['Downtime (hrs/day)', 'Max 2 hrs'],
                ['Permeate TDS', 'Max 500 ppm'],
                ['Permeate pH', 'Min 6.5 / Max 8.5'],
                ['Raw turbidity', 'Max 5 NTU'],
                ['Î”P (differential pressure)', 'Max 15 psi'],
                ['Recovery %', 'Min 70%'],
                ['PV ratio', 'Max 1.2'],
                ['Chemical stock (days remaining)', 'Min 7 days'],
              ]}
            />
            <P>
              Running an evaluation â€” Technician and above â€” takes a scope (global or one plant) and a window
              in days, then returns an overall compliant/breached banner, a 0â€“100 Compliance Score, period
              averages with trend arrows against the previous window, and a list of any specific violations.
              Editing the thresholds themselves is Manager/Admin only, and doesn&rsquo;t retroactively change
              evaluations already run. The{' '}
              <strong className="font-sans font-semibold not-italic">What-if</strong> tab is for planning: type
              a hypothetical value into any metric and watch the violation list and score update live, without
              saving anything or waiting on new data â€” useful for figuring out exactly how much a metric needs
              to improve to clear compliance.
            </P>
          </>
        ),
      },
      {
        id: 'admin-console',
        number: 21,
        title: 'Admin Console',
        dek: "The system's control room for accounts, plants, and audit history",
        body: (
          <>
            <Lead>
              What you see here depends entirely on role. Admin gets five tabs â€” Users, Plants, Audit,
              Migrations, and Roles. Manager gets two â€” Plants and Audit only, no user management, no
              migrations. Data Analyst is redirected to Data Corrections instead. Technician and Operator have
              no access at all.
            </Lead>
            <H3>Approving and managing users</H3>
            <P>
              New sign-ups arrive as Pending, defaulting internally to the Operator role; an Admin reviews the
              account, sets its real role, and approves it â€” at which point the person can sign in immediately.
              An Admin can also create a user directly, skipping self-signup entirely, for someone who can&rsquo;t
              register themselves. Existing users, grouped by role, offer row actions to change their role,
              password, email, or plant assignments.
            </P>
            <H3>The soft / hard / force delete pattern</H3>
            <P>
              User and plant deletion follows the same three-tier pattern everywhere in the app.{' '}
              <strong className="font-sans font-semibold not-italic">Soft delete</strong> marks a record
              inactive â€” reversible, and never blocked. <strong className="font-sans font-semibold not-italic">Hard
              delete</strong> permanently removes it, but is automatically blocked if dependent records exist
              (a user who&rsquo;s recorded readings, a plant with wells attached) â€” the dialog lists exactly
              what&rsquo;s in the way. <strong className="font-sans font-semibold not-italic">Force delete</strong>{' '}
              overrides that block with an explicit acknowledgement checkbox, cascading through dependent
              records â€” this cannot be undone, and is written to the Audit tab with a visible FORCE flag.
            </P>
            <H3>Roles, Audit, and Migrations</H3>
            <P>
              The <strong className="font-sans font-semibold not-italic">Roles</strong> tab, Admin-only, is
              where named custom roles get built on top of a system role â€” kept out of Manager&rsquo;s reach
              since a role editor can grant access to everything else. The{' '}
              <strong className="font-sans font-semibold not-italic">Audit</strong> tab is specifically a
              deletion log â€” every soft, hard, and force delete performed anywhere, with actor, timestamp,
              reason, and a FORCE badge where relevant; day-to-day correction history lives in Data Corrections
              instead (Chapter 17). The{' '}
              <strong className="font-sans font-semibold not-italic">Migrations</strong> tab is a technical
              utility for whoever administers the underlying database â€” not a day-to-day operations screen.
            </P>
          </>
        ),
      },
      {
        id: 'profile',
        number: 22,
        title: 'My Profile',
        dek: 'Your own identity, access level, and assigned plants',
        body: (
          <>
            <Lead>
              Every signed-in user has a Profile page, reachable from the sidebar or the account menu, showing
              your active plant, role and computed access level, identity details, email, and assigned plants.
            </Lead>
            <P>
              You can edit your own first/middle/last name, suffix, username, and designation at any time. If
              you&rsquo;re a non-operator, you can also change your own login email directly from this page;
              shared-device Operators should ask an Admin instead, since that email is shared across everyone
              on the crew. Your list of assigned plants is shown for reference but is read-only â€” changing it
              requires an Admin.
            </P>
          </>
        ),
      },
    ],
  };


