// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseFetch } from '@/lib/supabaseFetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

export const supabaseConfigError: string | null =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? 'Supabase environment variables are not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY, then redeploy.'
    : null;

if (supabaseConfigError && typeof console !== 'undefined') {
  console.error('[supabase]', supabaseConfigError);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Fall back to harmless placeholders so module evaluation does not throw
// when env vars are missing. The app renders a configuration banner instead
// of a blank white screen, and any actual Supabase call will surface a
// readable error rather than crashing on import.
export const supabase: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL ?? 'http://localhost.invalid',
  SUPABASE_PUBLISHABLE_KEY ?? 'missing-anon-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    // Outage circuit breaker (lib/apiHealth.ts): short-circuits REST reads while the
    // backend is down. NOTE: this file is marked auto-generated — if it is ever
    // regenerated, re-add this option or the breaker silently stops working.
    global: { fetch: supabaseFetch },
  },
);
